openapi: "3.0.0"

info:
  version: 0.0.1
  title: Poker Gamer Api
  contact:
    name: jeka
    email: team@jeka.ru

servers:
  - url: http://localhost:8080/

paths:

  /api/gamer/create:
    get:
      operationId: createGamer
      responses:
        '200':
          description: Создание игрока
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NwkGamer"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NwkError"

components:

  schemas:

    NwkGamer:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
      required:
        - id
        - createdAt

    NwkError:
      type: object
      description: Описание ошибки
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Код ошибки
        message:
          type: string
          description: Сообщение об ошибке